### ISSUE TITLE
Replace jq with shell alternative

### ISSUE THREAD

**Issue by Generator** [Generator/tautulli2trakt#1]
Replace `jq` with an shell alternative to make it Docker friendly

**Comment by nemchik** [comment]
Here is a snip from a script I wrote to read a specific value from a JSON response:

```
AVAILABLE_YQ=$( (curl -H "${GH_HEADER:-}" -fsL "https://api.github.com/repos/mikefarah/yq/releases/latest" | grep -Po '"tag_name": "[Vv]?\K.*?(?=")') || echo "0")
```

This could possibly be adapted to read other values from JSON depending on the formatting of newlines and such.

**Comment by Generator** [comment]
Thanks, that look to be a simple approach.  
For further information here's a sample json to parse
```
{"access_token": "dbaf9757982a9e738f05d249b7b5b4a266b3a139049317c4909f2f263572c781",  "token_type": "bearer",  "expires_in": 7200,  "refresh_token": "76ba4c5c75c96f6087f58a4de10be6c00b29ea1ddc3b2022ee2016d1363e3a7c",  "scope": "public",  "created_at": 1487889741}
```
The output is single line, and send values of `access_token`,  `refresh_token` and `created_at` to data file.

Trakt API docs 
https://trakt.docs.apiary.io/#reference/authentication-devices/device-code/generate-new-device-codes

**Comment by nemchik** [comment]
```
echo '{"access_token": "dbaf9757982a9e738f05d249b7b5b4a266b3a139049317c4909f2f263572c781",  "token_type": "bearer",  "expires_in": 7200,  "refresh_token": "76ba4c5c75c96f6087f58a4de10be6c00b29ea1ddc3b2022ee2016d1363e3a7c",  "scope": "public",  "created_at": 1487889741}' | grep -Po '"access_token": "\K.*?(?=")'
```

Should work.

**Comment by nemchik** [comment]
Btw this would fail in a scenario where an escaped quote `\"` is part of the value. The regex could be improved to handle this, but I haven't run into a need for it yet. If it's a concern for your purposes I can put the effort in.

**Comment by Generator** [comment]
That's it with multiple pattern
```
grep -Po '"access_token": "\K.*?(?=")|"refresh_token": "\K.*?(?=")|"created_at": \K.*?(?=})'
```

**Comment by nemchik** [comment]
wouldn't you want to recognize each pattern individually?

ex:
https://github.com/Generator/tautulli2trakt/blob/8f85482173ddccae4111f2ae7838d5b06b666780/tautulli2trakt.sh#L92
would be
```
echo DEVICE_CODE=$(grep -Po '"device_code": "\K.*?(?=")' /tmp/$SCRIPTNAME.tmp) > "$SCRIPTPATH/$SCRIPTNAME.data"
```
---
https://github.com/Generator/tautulli2trakt/blob/8f85482173ddccae4111f2ae7838d5b06b666780/tautulli2trakt.sh#L98
would be
```
USER_CODE=$(grep -Po '"user_code": "\K.*?(?=")' /tmp/$SCRIPTNAME.tmp)
```
---
For https://github.com/Generator/tautulli2trakt/blob/8f85482173ddccae4111f2ae7838d5b06b666780/tautulli2trakt.sh#L132 I would redirect this output to a temporary location and then read each value from it individually. `created_at` seems to be a bit of a different case as it's always a numeric value and the response you're getting doesn't encase numeric values in quotes. For that you could use `grep -Po '"created_at": \K\d+'`

**Comment by nemchik** [comment]
If you really want it inline you could shorten it a bit:
```
grep -Po '"(access_token|refresh_token)": "\K.*?(?=")|"created_at": \K\d+'
```
This will pull the matches out in whatever order they are given. So if you needed `refresh_token` first this would not work (neither would the original example you made https://github.com/Generator/tautulli2trakt/issues/1#issuecomment-527939996 ). This is why I think it makes more sense to store the output and then grep from it multiple times to individually pull out the pieces you want.
