### ISSUE TITLE
Entire sync

### ISSUE THREAD

**Issue by camjac251** [Generator/tautulli2trakt#12]
If you plan to add more to this cool tool, would it be possible to sync history from tautulli to trakt?
I had to revert to an old database because of a corruption that was happening for 2 months. My tautulli logs are still there but both plex and trakt end before 2 months ago so I have to mark everything as watched manually.

Having a tool that could sync from Tautulli to Trakt from the history would be incredibly useful. It could even get the ones that Plex missed or before the trakt scrobble tool was added.

**Comment by Generator** [comment]
https://github.com/Generator/tautulli2trakt/wiki/Frequently-Asked-Questions#q-can-i-push-all-my-tautulli-watch-history-to-trakttv

**Comment by camjac251** [comment]
I did see that in the FAQ but this issue was more of a feature request? Is this something that you'd find useful enough to develop?

**Comment by camjac251** [comment]
Also was hoping this could stay open as a feature request as it is not solved

**Comment by Generator** [comment]
Simply not possible, since the script is only trigged by Tautulli  when a new start watching/resume/stop.
