### ISSUE TITLE
Exit with code 127

### ISSUE THREAD

**Issue by justinglock40** [Generator/tautulli2trakt#14]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/23133649/104835356-09df1e80-5874-11eb-89d0-476793851cb0.png">

**Comment by justinglock40** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/23133649/104835367-1cf1ee80-5874-11eb-92eb-224ef4fa91c4.png">

**Comment by Generator** [comment]
That error isn't related with tautulli2trakt.  
It's from kill_stream.py and Tautulli

**Comment by justinglock40** [comment]
I disabled that script and it still happens and my history is not being sent to Trakt. Any trouble shooting tips?

**Comment by Generator** [comment]
You can try it directly from command line:
`./tautulli2trakt.sh -m episode -s "Chernobyl" -M "Chernobyl - 1:23:45" -y "2019" -t "360893" -i "tt7366338" -S 1 -E 1 -P 25 -a start`

And check your trakt.tv profile to confirm if its scrobbling https://trakt.tv/users/<username>

To stop progress:
`./tautulli2trakt.sh -m episode -s "Chernobyl" -M "Chernobyl - 1:23:45" -y "2019" -t "360893" -i "tt7366338" -S 1 -E 1 -P 25 -a stop`
