### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by snickers2k** [Generator/tautulli2trakt#4]
Hey.
Great job.
Since trakt-scrobbler already lost most of it's functionality (thanks plex),
i'm wondering if you have any plans for "two-way-sync" aswell as creating/syncing Playlists on Plex etc.

thanks

**Comment by Generator** [comment]
No, tautulli2trakt is triggered by Tautulli notifications, only can send data to trakt.tv.  
That's described on the [FAQ](https://github.com/Generator/tautulli2trakt/wiki/Frequently-Asked-Questions)  

> Q: Can i pull my watch history from Trakt.tv to Tautulli?
> A: No, tautulli2trakt only syncs one way (Tautulli to Trakt.tv)

Is not possible to pull data from trakt.tv to Plex.  

Other plans is to add new items to collection #3
