### ISSUE TITLE
Tautulli error and info not making it to trakt.tv

### ISSUE THREAD

**Issue by Tharic99** [Generator/tautulli2trakt#6]
I have a feeling this is something I did wrong, but who knows. I walked through the configuration twice now, making sure I removed everything in between each step.

When I watch something and it completes, I'm getting an error in my Tautulli logs and nothing ever shows up on trakt.tv for me.

I've got a custom condition on the script settings that looks if a user is <user 1> or is <user 2> but that looks like it's running okay in the logs. 

It's really the `Script error: grep: unrecognized option: P` that comes up consistently. 

[tautulli.log](https://github.com/Generator/tautulli2trakt/files/3683381/tautulli.log)

Thanks!

**Comment by Generator** [comment]
What system are you running, is it on Docker or on host?

**Comment by Tharic99** [comment]
Tautulli itself is on Docker, the script itself is sitting on the host via the path mapping.

**Comment by Generator** [comment]
Docker [tautulli/tautulli](https://hub.docker.com/r/tautulli/tautulli) doesn't support `-P, --perl-regexp  PATTERNS are Perl regular expressions`.  

I will try to find a different way to do it.

**Comment by Tharic99** [comment]
I'm on the [linuxserver/tautulli](https://hub.docker.com/r/linuxserver/tautulli) if that helps but it may very well be the same way.

**Comment by Generator** [comment]
Basically the same thing, both uses grep from busybox (1.30.1) and doesn't support perl regex expressions

**Comment by Generator** [comment]
@Tharic99 test the develop version 
```
wget -O tautulli2trakt.sh https://raw.githubusercontent.com/Generator/tautulli2trakt/develop/tautulli2trakt.sh  
chmod +x tautulli2trakt.sh
```

You'll need to run setup again, the previous didn't create a proper data file.  
First: `tautulli2trakt.sh --reset`  
Then: `tautulli2trakt.sh --setup`  

If it's working you should see the watch progress on your trakt.tv profile `https://trakt.tv/users/<your username>`

**Comment by Tharic99** [comment]
Did it all. Still not seeing anything though.

1. I noticed that my tautulli2trakt.data is 0 bytes. Even after multiple starts, pauses, etc.

2. I'm not seeing errors per say in the Tautulli logs though.

```

2019-10-04 17:33:27 | 12 | scripts | on_pause | -m episode -s "Chernobyl" -M "Chernobyl - 1:23:45" -y "2019" -t "360893" -i "tt7366338" -S 1 -E 1 -P 25 -a pause
-- | -- | -- | -- | --

```

But i'm not seeing anything new show up on my trakt.tv history. 
Feel free to check it yourself, it should be open to anyone.
https://trakt.tv/users/rs5050/history

**Comment by Generator** [comment]
> I noticed that my tautulli2trakt.data is 0 bytes

The file is probably empty, original file is 9k  

try instead 
`curl https://raw.githubusercontent.com/Generator/tautulli2trakt/develop/tautulli2trakt.sh -o tautulli2trakt.sh
chmod +x tautulli2trakt.sh `

**Comment by Tharic99** [comment]
Same thing, 0 byte data file. 

I even did the --reset and --setup again as well, still 0 bytes.

**Comment by Generator** [comment]
Sorry, misread the filename.  
do `cat tautulli2trakt.data`, you should see something like this:   
`{"access_token":"dbaf9757982a9e738f05d249b7b5b4a266b3a139049317c4909f2f263572c781","token_type":"bearer","expires_in":7200,"refresh_token":"76ba4c5c75c96f6087f58a4de10be6c00b29ea1ddc3b2022ee2016d1363e3a7c","scope":"public","created_at":1487889741}
`

but **dot not post here**, is just to check is the data is there

Tf there's any data you can try to run the command manualy and check your trakt.tv profile
`./tautulli2trakt.sh -m episode -s "Chernobyl" -M "Chernobyl - 1:23:45" -y "2019" -t "360893" -i "tt7366338" -S 1 -E 1 -P 25 -a start`

Stop action  
`./tautulli2trakt.sh -m episode -s "Chernobyl" -M "Chernobyl - 1:23:45" -y "2019" -t "360893" -i "tt7366338" -S 1 -E 1 -P 25 -a stop`

**Comment by Tharic99** [comment]
The `tautulli2trakt.data` is a zero byte file, so a `cat tautulli2trakt.data` doesn't return anything.

When I run the command manually, I get a date: invalid date ‘@’
```
./tautulli2trakt.sh -m episode -s "Chernobyl" -M "Chernobyl - 1:23:45" -y "2019" -t "360893" -i "tt7366338" -S 1 -E 1 -P 25 -a start
date: invalid date ‘@’
```

**Comment by Generator** [comment]
OK, some is wrong, will fix and do a proper testing. I'll try to fix this soon as possible

**Comment by Generator** [comment]
@Tharic99 Try it now. Found the issue, was just a typo.  
```
curl https://raw.githubusercontent.com/Generator/tautulli2trakt/develop/tautulli2trakt.sh -o tautulli2trakt.sh  
chmod +x tautulli2trakt.sh
```

then run again `tautulli2trakt.sh --setup`

**Comment by Generator** [comment]
New version release, you can try it  
`wget -O tautulli2trakt.sh https://raw.githubusercontent.com/Generator/tautulli2trakt/master/tautulli2trakt.sh
chmod +x tautulli2trakt.sh`

And run `tautulli2trakt.sh --setup`
